spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_SCHEMA:simple_app}
    username: ${DB_USER:root}
    password: ${DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: ${SERVER_PORT:8080}
